#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))

require 'pathname'
require 'thor'
require 'yaml'

require 'sprit_watch/formatter'
require 'sprit_watch/price_presenter'
require 'sprit_watch/client'

module SpritWatch
  class CLI < Thor
    desc 'list', 'List stations within the given coordinates'
    option :latitude, type: :numeric, required: true, desc: 'Latitude to search from'
    option :longitude, type: :numeric, required: true, desc: 'Longitude to search from'
    option :radius, type: :numeric, default: 2, desc: 'Search radius in km'
    option :closed, type: :boolean, default: false, desc: 'Include stations that are currently closed'
    option :format, type: :string, default: 'short', desc: "Format of the output; one of #{SpritWatch::Formatter.formats.join(', ')}"
    # TODO: option :fuel, type: :array, default: :all, desc: 'Fuel type (e5, e10, diesel, all). Multiple types can be given if separated by a space.'
    # TODO sort by price
    # TODO sort by distance
    long_desc 'List all stations within a radius of the given coordinates.'
    def list
      # warn "Stations within #{options[:radius]} km of #{options[:latitude]}, #{options[:longitude]}:"
      client.list(list_options(options)).each do |station|
        # TODO: print distance to point of origin
        puts SpritWatch::Formatter.formatter(options[:format]).format(station)
      end
    end

    desc 'prices', 'List prices for the preferred stations (listed in ~/.spritwatch.yml.)'
    # TODO: option :closed, type: :boolean, default: false, desc: 'Include stations that are currently closed'
    TYPES.each do |type|
      option type, type: :boolean, default: nil, desc: "Include #{type} prices"
    end
    def prices
      stations = client.prices(preferred_stations).reject(&:closed?)
      preferred_types = preferred_types(options)
      PricePresenter.find(preferred_types).present(stations)
    end

    private

    def list_options(options)
      {
        latitude: options[:latitude],
        longitude: options[:longitude],
        radius: options[:radius],
        closed: options[:closed]
      }
    end

    def client
      SpritWatch::Client.new(ENV.fetch('TANKERKOENIG_API_KEY'))
    end

    # TODO: Dupe
    def preferences
      YAML.load_file(Pathname('~/.spritwatch.yml').expand_path)
    end

    def preferred_types(options)
      (preferences['types'].map(&:to_sym) || TYPES).tap do |preferred_types|
        TYPES.each do |type|
          augment_types(preferred_types, options[type], type)
        end
      end.uniq
    end

    def augment_types(preferred_types, option, augment_with)
      case option
      when nil
        preferred_types # no change
      when true
        preferred_types.prepend(augment_with)
      when false
        preferred_types.delete(augment_with)
      else
        raise "Unexpected option #{option}"
      end
    end

    def preferred_stations
      preferences['stations'].map { |s| s['id'] }
    end
  end
end

SpritWatch::CLI.start(ARGV)
