#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))

require 'pathname'
require 'sprit_watch'
require 'thor'
require 'yaml'

module SpritWatch
  class CLI < Thor
    desc 'list', 'List stations within the given coordinates'
    option :latitude, type: :numeric, required: true, desc: 'Latitude to search from'
    option :longitude, type: :numeric, required: true, desc: 'Longitude to search from'
    option :radius, type: :numeric, default: 2, desc: 'Search radius in km'
    option :closed, type: :boolean, default: false, desc: 'Include stations that are currently closed'
    option :format, type: :string, default: 'short', desc: "Format of the output; one of #{SpritWatch::Formatter.formats.join(', ')}"
    # TODO: option :fuel, type: :array, default: :all, desc: 'Fuel type (e5, e10, diesel, all). Multiple types can be given if separated by a space.'
    # TODO sort by price
    # TODO sort by distance
    long_desc 'List all stations within a radius of the given coordinates.'
    def list
      # warn "Stations within #{options[:radius]} km of #{options[:latitude]}, #{options[:longitude]}:"
      client.list(list_options(options)).each do |station|
        # TODO: print distance to point of origin
        puts SpritWatch::Formatter.formatter(options[:format]).format(station)
      end
    end

    desc 'prices', 'List prices for the preferred stations (listed in ~/.spritwatch.yml.)'
    # TODO: option :closed, type: :boolean, default: false, desc: 'Include stations that are currently closed'
    TYPES.each do |type|
      option type, type: :boolean, default: nil, desc: "Include #{type} prices"
    end
    def prices
      preferred_stations = preferences['stations'].map { |s| s['id'] }
      stations = client.prices(preferred_stations).reject(&:closed?)
      preferred_types = preferred_types(options)
      warn 'Warning: Evaluation of preferred types and command-line switches yields an empty list' if preferred_types.empty?
      preferred_types.each do |type|
        sorted = stations.sort { |a, b| a.price(type) <=> b.price(type) }
        print_by_type(type, sorted)
      end
    end

    private

    def list_options(options)
      {
        latitude: options[:latitude],
        longitude: options[:longitude],
        radius: options[:radius],
        closed: options[:closed]
      }
    end

    def client
      SpritWatch::Client.new(ENV.fetch('TANKERKOENIG_API_KEY'))
    end

    def preferences
      YAML.load_file(Pathname('~/.spritwatch.yml').expand_path)
    end

    def print_by_type(type, prices)
      warn "#{type.to_s.capitalize}:"

      prices.each do |station|
        # TODO: Do not include the type if multiple types are given and we print the type above
        # TODO: Do not indent if only one type is given
        puts "  #{station_name(station.id)}: #{station.price(type.to_sym)}"
      end
    end

    # TODO: This may fail; we may need to look it up via #details or use a NullName (falling back to the station's id)
    def station_name(id)
      preferences['stations'].select { |h| h['id'] == id }.first['name']
    end

    def preferred_types(options)
      (preferences['types'].map(&:to_sym) || TYPES).tap do |preferred_types|
        TYPES.each do |type|
          case options[type]
          when nil
            # no change
          when true
            preferred_types.prepend(type)
          when false
            preferred_types.delete(type)
          else
            raise "Unexpected option #{options[type]}"
          end
        end
      end.uniq
    end
  end
end

SpritWatch::CLI.start(ARGV)
